(() => {
  const URL='https://glonbvrcudwuzjundrii.supabase.co',KEY='sb_publishable_VZbed_uuOXSE744UrAfHXw_z2xDdYtr',BUCKET='site-code'; let client;
  const escapeHTML=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  async function init(){if(!client&&window.parent!==window)client=window.parent.supabaseClient||null;if(!client){if(!window.supabase?.createClient)throw Error('Supabase library did not load.');client=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}})}const{data}=await client.auth.getSession();if(!data.session)throw Error('Sign in to the main dashboard first.');return client}
  const normalize=x=>({...x,lead_id:x.crmid||'',contact_name:x.original?.contact_name||'',contactName:x.original?.contact_name||'',status:x.stage||'staging',return_note:x.notes||'',returnNote:x.notes||'',review_checks:x.checks||{},checks:x.checks||{},live_at:x.original?.live_at||'',liveAt:x.original?.live_at||'',client_data:x.returndata||{},clientData:x.returndata||{},created_at:x.created,updated_at:x.updated,admin_url:x.adminurl||'',admin_status:x.adminstatus||'',admin_checked:x.adminchecked||'',admin_final_url:x.adminfinalurl||''});
  async function list(statuses=[]){await init();let q=client.from('sites').select('*').order('created',{ascending:true});if(statuses.length)q=q.in('stage',statuses);const{data,error}=await q;if(error)throw error;return(data||[]).map(normalize)}
  async function listBilling(){await init();const{data,error}=await client.from('square').select('*, payments(*)').in('status',['ACTIVE','CANCELED','PAUSED','DEACTIVATED','PENDING']).order('created',{ascending:true});if(error)throw error;return(data||[]).map(x=>({...x,user_id:x.userid,site_project_id:x.crmid,square_customer_id:x.customerid,square_subscription_id:x.subscriptionid,customer_name:x.name,customer_company:x.company,customer_email:x.email,customer_phone:x.phone,plan_name:x.plan,amount_money:x.amount,billing_cadence:x.cadence,start_date:x.startdate,canceled_date:x.canceled,charged_through_date:x.chargedthrough,created_at:x.created,updated_at:x.updated,payment_history:(x.payments||[]).map(p=>({...p,paid_at:p.paid,card_brand:p.card,card_last_4:p.lastfour,receipt_url:p.receipt,created_at:p.created,updated_at:p.updated}))}))}
  async function listAgreements(){await init();const{data,error}=await client.from('agreements').select('*').order('signed',{ascending:false});if(error)throw error;return(data||[]).map(x=>({...x,user_id:x.userid,signer_name:x.name,business_name:x.company,signer_email:x.email,electronic_signature:x.signature,plan_label:x.plan,terms_version:x.terms,agreement_snapshot:x.document,signed_at:x.signed,created_at:x.created}))}
  async function listClientSites(){await init();const{data,error}=await client.from('sites').select('*').order('created',{ascending:true});if(error)throw error;return(data||[]).map(x=>({...x,user_id:x.userid,site_name:x.name,site_key:x.sitekey,public_url:x.liveurl||x.previewurl,admin_url:x.adminurl,admin_status:x.adminstatus,admin_checked:x.adminchecked,admin_final_url:x.adminfinalurl,domain_name:x.domain,domain_status:x.domainstatus,status:x.stage,created_at:x.created,updated_at:x.updated}))}
  async function saveClientSite(s){await init();const sourceid=`portal:${s.userId}:${s.siteKey}`,row={userid:s.userId,source:'portal',sourceid,sitekey:s.siteKey,name:s.siteName,previewurl:s.publicUrl||null,liveurl:s.publicUrl||null,adminurl:s.adminUrl||null,domain:s.domainName||null,domainstatus:s.domainActive?'active':'inactive',stage:'active',updated:new Date().toISOString()};const{data,error}=await client.from('sites').upsert(row,{onConflict:'source,sourceid'}).select().single();if(error)throw error;return data}
  async function create(p){await init();const{data,error}=await client.from('sites').insert({crmid:p.leadId||null,source:'dashboard',sourceid:crypto.randomUUID(),sitekey:p.sitekey||null,name:p.company||'',previewurl:p.previewurl||null,adminurl:p.adminurl||null,adminstatus:p.adminstatus||null,stage:'staging',original:{contact_name:p.contactName||'',email:p.email||'',phone:p.phone||''}}).select().single();if(error)throw error;return normalize(data)}
  async function update(id,changes){await init();const row={updated:new Date().toISOString()};if('status'in changes)row.stage=changes.status;if('files'in changes)row.files=changes.files;if('checks'in changes)row.checks=changes.checks;if('returnNote'in changes)row.notes=changes.returnNote;if('clientData'in changes)row.returndata=changes.clientData;for(const k of['sitekey','name','previewurl','liveurl','adminurl','adminstatus','adminchecked','adminfinalurl','domain','domainstatus'])if(k in changes)row[k]=changes[k];const{error}=await client.from('sites').update(row).eq('id',id);if(error)throw error;return{...changes,id}}
  async function remove(id){await init();const{error}=await client.from('sites').delete().eq('id',id);if(error)throw error}
  async function upload(id,path,file){await init();const{error}=await client.storage.from(BUCKET).upload(`${id}/${path}`,file,{upsert:true,contentType:file.type||'application/octet-stream'});if(error)throw error}
  async function download(id,path){await init();const{data,error}=await client.storage.from(BUCKET).download(`${id}/${path}`);if(error)throw error;return data}
  async function removeFiles(id,files){await init();const paths=(files||[]).map(f=>`${id}/${f.path}`);if(!paths.length)return;const{error}=await client.storage.from(BUCKET).remove(paths);if(error)throw error}
  window.SitePipeline={init,list,listBilling,listAgreements,listClientSites,saveClientSite,create,update,remove,upload,download,removeFiles,escapeHTML};
})();
