(() => {
 const labels=[['responsive','Mobile and desktop verified'],['links','Links, forms, and buttons tested'],['content','Content and contact details verified'],['console','No console errors or broken assets']];
 let items=[];
 const root=document.getElementById('queue'),status=document.getElementById('status');
 const msg=(t,e=false)=>{status.textContent=t;status.classList.toggle('error',e)};
 const siteKey=x=>String(x.sitekey||x.site_slug||x.slug||'').trim();
 const githubBase=x=>siteKey(x)?`Sites/${siteKey(x)}/`:'';
 const defaultMode=x=>(x.files||[]).some(f=>/^admin(?:\.html|\/)/i.test(String(f?.path||'')))?'admin':'site';
 const publishTarget=(x,f,mode)=>{const base=githubBase(x),path=String(f?.path||'').replace(/^\/+/, '');if(mode==='admin'){const p=path.replace(/^admin\//i,'');return base+'admin/'+((/^admin\.html$/i.test(p)||/^index\.html$/i.test(p))?'index.html':p)}return base+path};
 async function load(){try{items=await SitePipeline.list(['review']);render()}catch(e){msg(e.message,true)}}
 function render(){root.innerHTML=items.map(x=>{const files=x.files||[],mode=defaultMode(x);return `<article class="review-grid card"><section class="review-panel"><div class="upload-head"><span class="badge">Under review</span><button class="btn secondary" data-download="${x.id}">Download All (.zip)</button></div><h2>${SitePipeline.escapeHTML(x.company||x.name||'Unnamed business')}</h2><div class="file-tree">${files.map(f=>`<span><i class="bi bi-file-earmark-code"></i><b>${SitePipeline.escapeHTML(f.path)}</b><small>${f.size} B</small></span>`).join('')||'<span><i class="bi bi-link-45deg"></i><b>No uploaded files yet</b></span>'}</div><textarea data-notes="${x.id}" placeholder="Review notes">${SitePipeline.escapeHTML(x.notes)}</textarea></section><aside class="review-panel"><h3>Verification checklist</h3><div class="review-list">${labels.map(([k,v])=>`<label><input type="checkbox" data-check="${k}" data-id="${x.id}" ${x.checks[k]?'checked':''}>${v}</label>`).join('')}</div><label class="stack-label">Site key<input class="text-input" data-sitekey="${x.id}" value="${SitePipeline.escapeHTML(siteKey(x))}"></label><label class="stack-label">Publish as<select class="text-input" data-mode="${x.id}"><option value="site" ${mode==='site'?'selected':''}>Regular Site</option><option value="admin" ${mode==='admin'?'selected':''}>Admin Page</option></select></label><div class="card" style="padding:12px;margin-top:10px"><strong>GitHub destination</strong><div data-targets="${x.id}" style="margin-top:7px;color:#8eb4dc;font-size:12px">${files.length?files.map(f=>`<div><code>${SitePipeline.escapeHTML(publishTarget(x,f,mode))}</code></div>`).join(''):'Upload files before publishing.'}</div></div><div class="review-actions"><button class="btn secondary" data-return="${x.id}">Return to Staging</button><button class="btn" data-publish="${x.id}">Publish to ViewYourSite</button></div></aside></article>`}).join('')||'<div class="empty"><div><i class="bi bi-code-square"></i><strong>No sites under review.</strong></div></div>'}
 async function zip(x){if(!(x.files||[]).length)return msg('There are no files to download.',true);const z=new JSZip();for(const f of x.files||[])z.file(f.path,await SitePipeline.download(x.id,f.path));const blob=await z.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(x.company||x.name||'site').replace(/\W+/g,'-')}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 function refreshTargets(x,mode){const box=root.querySelector(`[data-targets="${x.id}"]`);if(!box)return;box.innerHTML=(x.files||[]).length?(x.files||[]).map(f=>`<div><code>${SitePipeline.escapeHTML(publishTarget(x,f,mode))}</code></div>`).join(''):'Upload files before publishing.'}
 root.addEventListener('change',async e=>{const id=e.target.dataset.id||e.target.dataset.sitekey||e.target.dataset.mode;const x=items.find(i=>i.id===id);if(!x)return;if(e.target.dataset.check){x.checks[e.target.dataset.check]=e.target.checked;await SitePipeline.update(x.id,{checks:x.checks})}if(e.target.dataset.sitekey!==undefined){x.sitekey=e.target.value.trim();await SitePipeline.update(x.id,{sitekey:x.sitekey})}if(e.target.dataset.mode!==undefined)refreshTargets(x,e.target.value);if(e.target.dataset.mode===undefined)load()});
 root.addEventListener('input',e=>{const x=items.find(i=>i.id===e.target.dataset.notes);if(x)x.notes=e.target.value});
 root.addEventListener('focusout',async e=>{const x=items.find(i=>i.id===e.target.dataset.notes);if(x)await SitePipeline.update(x.id,{notes:x.notes})});
 root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
  if(b.dataset.download){await zip(items.find(i=>i.id===b.dataset.download));return}
  if(b.dataset.return){const note=prompt('Optional: add a note explaining what should be changed.','');if(note===null)return;await SitePipeline.update(b.dataset.return,{status:'staging',returnNote:note.trim(),checks:{responsive:false,links:false,content:false,console:false}});await load();return}
  if(b.dataset.publish){const x=items.find(i=>i.id===b.dataset.publish);if(!x)return;const missing=[];if(!siteKey(x))missing.push('site key');if(!(x.files||[]).length)missing.push('uploaded files');for(const [k,v] of labels)if(!x.checks[k])missing.push(v);if(missing.length){msg(`Before publishing: ${missing.join(' · ')}`,true);return}const mode=root.querySelector(`[data-mode="${x.id}"]`)?.value==='admin'?'admin':'site';b.disabled=true;b.textContent='Publishing…';msg(`Publishing ${x.company||x.name||siteKey(x)}…`);const client=await SitePipeline.init();const {data,error}=await client.functions.invoke('publish-viewyoursite',{body:{projectId:x.id,mode}});if(error)throw error;if(data?.error)throw new Error(data.error);await SitePipeline.update(x.id,{status:'published'});items=items.filter(i=>i.id!==x.id);render();msg(`Published successfully to ViewYourSite${data?.commitSha?` · ${data.commitSha.slice(0,7)}`:''}`);return}
 }catch(err){msg(err?.message||String(err),true);const publishBtn=b?.dataset?.publish?b:null;if(publishBtn){publishBtn.disabled=false;publishBtn.textContent='Publish to ViewYourSite'}}});
 load();
})();