(() => {
 const labels=[['responsive','Mobile and desktop verified'],['links','Links, forms, and buttons tested'],['content','Content and contact details verified'],['console','No console errors or broken assets']];let items=[];const root=document.getElementById('queue'),status=document.getElementById('status');const msg=(t,e=false)=>{status.textContent=t;status.classList.toggle('error',e)};
 const siteKey=x=>String(x.sitekey||x.site_slug||x.slug||'').trim();
 const githubBase=x=>siteKey(x)?`Sites/${siteKey(x)}/`:'';
 const publishTarget=(x,f)=>{const base=githubBase(x);const path=String(f?.path||'').replace(/^\/+/, '');if(/^admin\.html$/i.test(path))return base+'admin/index.html';if(/^admin\/index\.html$/i.test(path))return base+path;return base+path};
 async function load(){try{items=await SitePipeline.list(['review']);render()}catch(e){msg(e.message,true)}}
 function render(){root.innerHTML=items.map(x=>{const files=x.files||[],base=githubBase(x);return `<article class="review-grid card"><section class="review-panel"><div class="upload-head"><span class="badge">Under review</span><button class="btn secondary" data-download="${x.id}" ${files.length?'':'disabled'}>Download All (.zip)</button></div><h2>${SitePipeline.escapeHTML(x.company||x.name||'Unnamed business')}</h2><div class="file-tree">${files.map(f=>`<span><i class="bi bi-file-earmark-code"></i><b>${SitePipeline.escapeHTML(f.path)}</b><small>${f.size} B</small></span>`).join('')||'<span><i class="bi bi-link-45deg"></i><b>Linked CRM site — no uploaded files yet</b></span>'}</div><textarea data-notes="${x.id}" placeholder="Review notes">${SitePipeline.escapeHTML(x.notes)}</textarea></section><aside class="review-panel"><h3>Verification checklist</h3><div class="review-list">${labels.map(([k,v])=>`<label><input type="checkbox" data-check="${k}" data-id="${x.id}" ${x.checks[k]?'checked':''}>${v}</label>`).join('')}</div><label class="stack-label">Site key<input class="text-input" data-sitekey="${x.id}" value="${SitePipeline.escapeHTML(siteKey(x))}"></label><div class="card" style="padding:12px;margin-top:10px"><strong>GitHub publish target</strong><div style="margin-top:7px;color:#8eb4dc;font-size:12px">${files.length?files.map(f=>`<div><code>${SitePipeline.escapeHTML(publishTarget(x,f))}</code></div>`).join(''):(base?`<code>${SitePipeline.escapeHTML(base)}</code>`:'Add a site key to determine the target folder.')}</div></div><div class="review-actions"><button class="btn secondary" data-return="${x.id}">Return to Staging</button><button class="btn" data-ready="${x.id}" ${labels.every(([k])=>x.checks[k])&&siteKey(x)?'':'disabled'}>Ready for GitHub</button></div></aside></article>`}).join('')||'<div class="empty"><div><i class="bi bi-code-square"></i><strong>No sites under review.</strong></div></div>'}
 async function zip(x){const z=new JSZip();for(const f of (x.files||[]))z.file(f.path,await SitePipeline.download(x.id,f.path));const blob=await z.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(x.company||x.name||'site').replace(/\W+/g,'-')}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 root.addEventListener('change',async e=>{const id=e.target.dataset.id||e.target.dataset.sitekey;const x=items.find(i=>i.id===id);if(!x)return;if(e.target.dataset.check){x.checks[e.target.dataset.check]=e.target.checked;await SitePipeline.update(x.id,{checks:x.checks})}if(e.target.dataset.sitekey!==undefined){x.sitekey=e.target.value.trim();await SitePipeline.update(x.id,{sitekey:x.sitekey})}load()});
 root.addEventListener('input',e=>{const x=items.find(i=>i.id===e.target.dataset.notes);if(x)x.notes=e.target.value});
 root.addEventListener('focusout',async e=>{const x=items.find(i=>i.id===e.target.dataset.notes);if(x)await SitePipeline.update(x.id,{notes:x.notes})});
 root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.download&&!b.disabled)await zip(items.find(i=>i.id===b.dataset.download));if(b.dataset.return){const note=prompt('Optional: add a note explaining what should be changed.','');if(note===null)return;await SitePipeline.update(b.dataset.return,{status:'staging',returnNote:note.trim(),checks:{responsive:false,links:false,content:false,console:false}})}if(b.dataset.ready&&!b.disabled){const x=items.find(i=>i.id===b.dataset.ready);msg(`Ready for GitHub: ${githubBase(x)} Download the ZIP and publish it to the displayed target path.`)}await load()}catch(err){msg(err.message,true)}});load();
})();