(() => {
 const cards=document.getElementById('cards'),status=document.getElementById('status'),filePicker=document.getElementById('filePicker'),folderPicker=document.getElementById('folderPicker');let items=[],activeId='';const MAX=25*1024*1024,fmt=n=>n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`,size=x=>(x.files||[]).reduce((n,f)=>n+(f.size||0),0);
 const message=(t,e=false)=>{status.textContent=t;status.classList.toggle('error',e)};
 async function load(){try{items=await SitePipeline.list(['staging']);render()}catch(e){message(e.message.includes('site_projects')?'Run supabase-pipeline-setup.sql in Supabase first.':e.message,true)}}
 function render(){document.getElementById('capacityText').textContent=`${items.length} / 10`;document.getElementById('capacityMeter').style.width=`${items.length*10}%`;cards.innerHTML=items.map(x=>`<article class="card upload-card"><div class="upload-head"><div class="company"><strong>${SitePipeline.escapeHTML(x.company)}</strong><span>${SitePipeline.escapeHTML(x.contactName||'No contact')}</span></div><span class="badge">Staging</span></div>${x.returnNote?`<div class="return-note"><strong>Returned from Review</strong><span>${SitePipeline.escapeHTML(x.returnNote)}</span></div>`:''}<div class="drop-zone" data-drop="${x.id}"><i class="bi bi-envelope-arrow-up-fill"></i><strong>Drag and drop files or folders</strong><span>HTML, CSS, JS, pages, folders, and assets</span><div class="drop-actions"><button class="btn secondary" data-files="${x.id}">Choose Files</button><button class="btn secondary" data-folder="${x.id}">Choose Folder</button></div></div><div class="file-summary"><strong>${(x.files||[]).length} files · ${fmt(size(x))}</strong><span>25 MB maximum</span></div><div class="file-list">${(x.files||[]).map(f=>`<span><i class="bi bi-file-earmark-code"></i>${SitePipeline.escapeHTML(f.path)}<small>${fmt(f.size)}</small></span>`).join('')||'<em>No files attached.</em>'}</div><div class="review-actions"><button class="btn secondary" data-back="${x.id}">Back to Leads</button><button class="btn" data-review="${x.id}" ${x.files?.length?'':'disabled'}>Send to Review</button></div></article>`).join('')||'<div class="empty"><div><i class="bi bi-kanban"></i><strong>No live staging records.</strong><br>Forward a lead from the Leads page.</div></div>'}
 async function add(id,list){const x=items.find(i=>i.id===id),files=[...list].filter(f=>f.name!=='.DS_Store'&&!String(f.webkitRelativePath||f.pipelinePath).includes('node_modules')&&!String(f.webkitRelativePath||f.pipelinePath).includes('/.git/'));if(size(x)+files.reduce((n,f)=>n+f.size,0)>MAX)return message('This website exceeds 25 MB.',true);for(const f of files){const path=f.pipelinePath||f.webkitRelativePath||f.name;await SitePipeline.upload(id,path,f);const meta={path,size:f.size,type:f.type||'application/octet-stream'},at=(x.files||[]).findIndex(v=>v.path===path);x.files=x.files||[];at>=0?x.files[at]=meta:x.files.push(meta)}await SitePipeline.update(id,{files:x.files});message(`${files.length} files uploaded.`);load()}
 function entry(e,path=''){return new Promise(ok=>{if(e.isFile)e.file(f=>{f.pipelinePath=path+f.name;ok([f])});else{const r=e.createReader(),all=[];const next=()=>r.readEntries(async es=>{if(!es.length)return ok(all);for(const v of es)all.push(...await entry(v,`${path}${e.name}/`));next()});next()}})}async function dropped(dt){const es=[...(dt.items||[])].map(i=>i.webkitGetAsEntry?.()).filter(Boolean),out=[];if(!es.length)return[...dt.files];for(const e of es)out.push(...await entry(e));return out}
 cards.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.files){activeId=b.dataset.files;filePicker.click()}if(b.dataset.folder){activeId=b.dataset.folder;folderPicker.click()}if(b.dataset.review)await SitePipeline.update(b.dataset.review,{status:'review',returnNote:''});if(b.dataset.back){const x=items.find(i=>i.id===b.dataset.back);await SitePipeline.removeFiles(x.id,x.files);await SitePipeline.remove(x.id)}await load()}catch(err){message(err.message,true)}});for(const p of[filePicker,folderPicker])p.addEventListener('change',async()=>{await add(activeId,p.files);p.value=''});cards.addEventListener('dragover',e=>{if(e.target.closest('[data-drop]'))e.preventDefault()});cards.addEventListener('drop',async e=>{const z=e.target.closest('[data-drop]');if(!z)return;e.preventDefault();await add(z.dataset.drop,await dropped(e.dataTransfer))});load();
})();
