(() => {
  const style = document.createElement('style');
  style.textContent = `.auto-builder{margin:-15px -15px 18px;padding:22px;border:1px solid #2e8bff;border-radius:14px;background:linear-gradient(145deg,#08213c,#041323)}.auto-builder h3{margin:4px 0 7px;font-size:23px}.auto-builder p{margin:0;color:#9bbada;line-height:1.5}.auto-kicker{color:#73bdff;font-size:10px;font-weight:900;letter-spacing:.16em}.auto-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.auto-progress{display:none;margin-top:18px;padding:14px;border:1px solid #17436f;border-radius:11px;background:#03101e}.auto-progress.active{display:block}.auto-progress strong,.auto-progress span{display:block}.auto-progress span{margin-top:4px;color:#8eb4dc;font-size:12px}.auto-bar{height:5px;margin-top:12px;overflow:hidden;border-radius:99px;background:#123554}.auto-bar i{display:block;width:38%;height:100%;border-radius:inherit;background:linear-gradient(90deg,#2e8bff,#73bdff);animation:auto-load 1.25s ease-in-out infinite}.research-result{margin-top:15px}.research-result summary{cursor:pointer;color:#73bdff;font-weight:800}.research-result pre{max-height:310px;overflow:auto;white-space:pre-wrap;padding:13px;border:1px solid #17436f;border-radius:10px;background:#03101e;color:#dcecff;font:12px/1.5 system-ui}.btn,.back,.staging-lead{transition:transform .12s ease,filter .12s ease,box-shadow .12s ease}.btn:active,.back:active,.staging-lead:active,.btn.is-clicked,.back.is-clicked,.staging-lead.is-clicked{transform:scale(.96);filter:brightness(1.25);box-shadow:0 0 0 3px rgba(115,189,255,.28)}.build-files-title{margin:22px 0 12px;padding-top:18px;border-top:1px solid #17436f;color:#73bdff;font-size:12px;font-weight:900;letter-spacing:.12em}@keyframes auto-load{0%{transform:translateX(-110%)}50%{transform:translateX(130%)}100%{transform:translateX(300%)}}`;
  document.head.appendChild(style);

  const listEl=document.getElementById('stagingList'),status=document.getElementById('status'),filePicker=document.getElementById('filePicker'),folderPicker=document.getElementById('folderPicker');
  let leads=[],projects=[],active=null,activeProject=null,researchDraft='',building=false;
  const MAX=25*1024*1024;
  const fmt=n=>n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
  const size=x=>(x?.files||[]).reduce((n,f)=>n+(f.size||0),0);
  const message=(t,e=false)=>{status.textContent=t;status.classList.toggle('error',e);const detail=document.getElementById('detailStatus');if(detail){detail.textContent=t;detail.classList.toggle('error',e);detail.hidden=!t}};
  const previewUrl=(...values)=>{for(const value of values){const raw=String(value||'').trim();if(!raw)continue;try{const u=new URL(/^[a-z][a-z\d+.-]*:\/\//i.test(raw)?raw:`https://${raw}`),h=u.hostname.toLowerCase().replace(/^www\./,'');if(h==='viewyoursite.today'||h.endsWith('.viewyoursite.today'))return u.href}catch{}}return''};

  async function load(){try{const db=await SitePipeline.init(),[crm,sites]=await Promise.all([db.from('crm').select('*').order('company',{ascending:true}),SitePipeline.list()]);if(crm.error)throw crm.error;projects=sites;const mapped=new Map();for(const site of sites){const preview=previewUrl(site.previewurl,site.liveurl);if(preview&&site.lead_id&&!mapped.has(String(site.lead_id)))mapped.set(String(site.lead_id),preview)}leads=(crm.data||[]).filter(lead=>!previewUrl(lead.previewurl,lead.website,mapped.get(String(lead.id))));renderList();if(active){active=leads.find(lead=>lead.id===active.id)||null;if(active){activeProject=projects.find(item=>item.lead_id===active.id)||activeProject;renderDetail()}else showList()}}catch(error){message(error.message,true)}}
  function renderList(){const q=String(document.getElementById('stagingSearch').value||'').trim().toLowerCase(),matches=leads.filter(lead=>!q||[lead.company,lead.name,lead.phone,lead.email].some(value=>String(value||'').toLowerCase().includes(q)));message(`${matches.length} lead${matches.length===1?'':'s'} need a site`);listEl.innerHTML=matches.map(lead=>`<button class="card staging-lead" data-lead="${SitePipeline.escapeHTML(lead.id)}" type="button"><span class="staging-lead-icon"><i class="bi bi-buildings"></i></span><span><strong>${SitePipeline.escapeHTML(lead.company||'Unnamed business')}</strong><span>${SitePipeline.escapeHTML(lead.name||'No contact')} · ${SitePipeline.escapeHTML(lead.phone||'No phone')}</span></span><span class="needs-site">Needs Site</span></button>`).join('')||'<div class="empty"><div><i class="bi bi-check2-circle"></i><strong>Every CRM lead has a site preview.</strong></div></div>'}
  function showList(){active=null;activeProject=null;researchDraft='';building=false;document.getElementById('stagingDirectory').hidden=false;document.getElementById('stagingDetail').hidden=true;renderList();window.scrollTo({top:0,behavior:'smooth'})}
  function openLead(id){active=leads.find(lead=>String(lead.id)===String(id));if(!active)return;activeProject=projects.find(item=>String(item.lead_id)===String(active.id))||null;researchDraft='';building=false;document.getElementById('stagingDirectory').hidden=true;document.getElementById('stagingDetail').hidden=false;renderDetail();window.scrollTo({top:0,behavior:'smooth'})}
  function renderDetail(){document.getElementById('detailCompany').textContent=active.company||'Unnamed business';document.getElementById('detailContact').textContent=[active.name,active.email,active.phone].filter(Boolean).join(' · ')||'No contact information';const files=activeProject?.files||[];document.getElementById('uploadWorkspace').innerHTML=`<section class="auto-builder"><span class="auto-kicker">AI RESEARCH + WEBSITE</span><h3>Create ${SitePipeline.escapeHTML(active.company||'this website')}</h3><p>One click researches this business, submits the verified information, creates a complete responsive website, and saves <strong>index.html</strong> here.</p><div class="auto-actions"><button class="btn primary" data-auto-build type="button" ${building?'disabled':''}><i class="bi bi-stars"></i> ${files.some(f=>f.path==='index.html')?'Regenerate Website':'Research & Create Site'}</button></div><div class="status" id="detailStatus" hidden aria-live="polite"></div><div class="auto-progress ${building?'active':''}" aria-live="polite"><strong id="autoProgressTitle">Researching the business…</strong><span id="autoProgressText">Checking public sources, services, contact details, reviews and brand information. Website generation begins automatically. This may take several minutes.</span><div class="auto-bar"><i></i></div></div>${researchDraft?`<details class="research-result"><summary>View research used to create this site</summary><pre>${SitePipeline.escapeHTML(researchDraft)}</pre></details>`:''}</section><div class="build-files"><div class="build-files-title">WEBSITE FILES</div><div class="upload-head"><div class="company"><strong>${SitePipeline.escapeHTML(active.company||'Unnamed business')}</strong><span>${SitePipeline.escapeHTML(active.name||'No contact')}</span></div><span class="badge">Needs Site</span></div><div class="drop-zone" data-drop><i class="bi bi-envelope-arrow-up-fill"></i><strong>Drag and drop files or folders</strong><span>HTML, CSS, JS, pages, folders, and assets</span><div class="drop-actions"><button class="btn secondary" data-files>Choose Files</button><button class="btn secondary" data-folder>Choose Folder</button></div></div><div class="file-summary"><strong>${files.length} files · ${fmt(size(activeProject))}</strong><span>25 MB maximum</span></div><div class="file-list">${files.map(file=>`<span><i class="bi bi-file-earmark-code"></i>${SitePipeline.escapeHTML(file.path)}<small>${fmt(file.size)}</small></span>`).join('')||'<em>No files attached.</em>'}</div><div class="review-actions"><button class="btn" data-review ${files.length?'':'disabled'}>Send to Review</button></div></div>`}
  async function ensureProject(){if(activeProject)return activeProject;activeProject=await SitePipeline.create({leadId:active.id,company:active.company,contactName:active.name,email:active.email,phone:active.phone});projects.push(activeProject);return activeProject}
  async function saveFile(file,path=file.name){const project=await ensureProject();if(size(project)+file.size>MAX)throw Error('This website exceeds 25 MB.');await SitePipeline.upload(project.id,path,file);const meta={path,size:file.size,type:file.type||'application/octet-stream'},index=(project.files||[]).findIndex(item=>item.path===path);project.files=project.files||[];index>=0?project.files[index]=meta:project.files.push(meta);await SitePipeline.update(project.id,{files:project.files})}
  async function add(input){const files=[...input].filter(file=>file.name!=='.DS_Store'&&!String(file.webkitRelativePath||file.pipelinePath).includes('node_modules')&&!String(file.webkitRelativePath||file.pipelinePath).includes('/.git/'));for(const file of files)await saveFile(file,file.pipelinePath||file.webkitRelativePath||file.name);message(`${files.length} files uploaded.`);renderDetail()}
  async function autoBuild(){if(building)return;building=true;renderDetail();message('Researching and creating the website…');try{const db=await SitePipeline.init();const{data,error}=await db.functions.invoke('research-build-site',{body:{company:active.company||active.name}});if(error){let detail=error.message;try{const body=await error.context?.json();if(body?.error)detail=body.error}catch{}throw Error(detail)}if(data?.error)throw Error(data.error);if(!data?.html)throw Error('The generator returned no website file.');const title=document.getElementById('autoProgressTitle'),text=document.getElementById('autoProgressText');if(title)title.textContent='Saving index.html…';if(text)text.textContent='Research is complete. Uploading the generated website into this staging project.';researchDraft=data.research||'';const file=new File([data.html],'index.html',{type:'text/html'});await saveFile(file,'index.html');building=false;renderDetail();message('Website created and index.html saved. Open the research report or send the site to Review.')}catch(error){building=false;renderDetail();message(error.message||'Website generation failed.',true)}}
  function entry(item,path=''){return new Promise(resolve=>{if(item.isFile)item.file(file=>{file.pipelinePath=path+file.name;resolve([file])});else{const reader=item.createReader(),all=[];const next=()=>reader.readEntries(async entries=>{if(!entries.length)return resolve(all);for(const child of entries)all.push(...await entry(child,`${path}${item.name}/`));next()});next()}})}
  async function dropped(dt){const entries=[...(dt.items||[])].map(item=>item.webkitGetAsEntry?.()).filter(Boolean),out=[];if(!entries.length)return[...dt.files];for(const item of entries)out.push(...await entry(item));return out}
  listEl.onclick=e=>{const b=e.target.closest('[data-lead]');if(b)openLead(b.dataset.lead)};
  document.getElementById('backToStaging').onclick=showList;
  document.getElementById('stagingSearch').oninput=renderList;
  document.getElementById('uploadWorkspace').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-auto-build'))await autoBuild();if(b.hasAttribute('data-files'))filePicker.click();if(b.hasAttribute('data-folder'))folderPicker.click();if(b.hasAttribute('data-review')){const p=await ensureProject();await SitePipeline.update(p.id,{status:'review',returnNote:''});message('Sent to Review');showList()}};
  for(const picker of[filePicker,folderPicker])picker.onchange=async()=>{try{await add(picker.files)}catch(error){message(error.message,true)}picker.value=''};
  document.getElementById('uploadWorkspace').ondragover=e=>{if(e.target.closest('[data-drop]'))e.preventDefault()};
  document.getElementById('uploadWorkspace').ondrop=async e=>{if(!e.target.closest('[data-drop]'))return;e.preventDefault();try{await add(await dropped(e.dataTransfer))}catch(error){message(error.message,true)}};
  document.addEventListener('pointerdown',e=>{const button=e.target.closest('button');if(!button||button.disabled)return;button.classList.add('is-clicked');setTimeout(()=>button.classList.remove('is-clicked'),180)});
  load();
})();
