const SUPABASE_URL='https://glonbvrcudwuzjundrii.supabase.co';
const SUPABASE_KEY='sb_publishable_VZbed_uuOXSE744UrAfHXw_z2xDdYtr';
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let leads=[],active=null,directoryCategory='uncalled',siteFilterMode='has-site',tags=[],sources=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=(v,f='')=>String(v??'').trim()||f;
const normalize=v=>String(v||'').trim().toLowerCase().replace(/[\s_-]+/g,'');
function hasPreview(l){return l?.has_site_preview===true||Boolean(clean(l?.previewurl)||clean(l?.sitekey))}
function leadTags(l){return [...(Array.isArray(l?.tags)?l.tags:[]),...(Array.isArray(l?.sources)?l.sources:[])]}
function isNotInterested(l){return [...leadTags(l),l?.stage,l?.outcome].some(v=>normalize(v)==='notinterested')}
function leadCategory(l){if(isNotInterested(l))return'notinterested';return l?.lastcalled?'followups':'uncalled'}
function categoryLabel(c){return c==='notinterested'?'Not Interested':c==='followups'?'Follow Up':'Not Called'}
function lastCalledLabel(l){if(!l?.lastcalled)return clean(l?.phone,'No phone number');const d=new Date(l.lastcalled);return Number.isNaN(d.getTime())?'Previously called':'Last called '+d.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function renderDirectory(){const counts={uncalled:0,followups:0,notinterested:0};leads.forEach(l=>counts[leadCategory(l)]++);Object.entries(counts).forEach(([k,v])=>{const n=document.querySelector('[data-count="'+k+'"]');if(n)n.textContent=v});const needle=clean($('#directorySearch').value).toLowerCase();const matches=leads.filter(l=>leadCategory(l)===directoryCategory&&hasPreview(l)===(siteFilterMode==='has-site')&&(!needle||[l.company,l.name,l.phone,l.email,l.leadtype,...leadTags(l)].some(v=>String(v||'').toLowerCase().includes(needle))));$('#directoryStatus').textContent=`${matches.length} ${matches.length===1?'lead':'leads'} in ${directoryCategory==='uncalled'?'Leads Not Called':directoryCategory==='followups'?'Follow Ups':'Not Interested'} · ${siteFilterMode==='has-site'?'Has Site Preview':'Does Not Have Site Preview'}`;$('#leadList').innerHTML=matches.length?matches.map(l=>{const c=leadCategory(l),hp=hasPreview(l),sub=c==='notinterested'?'Marked Not Interested':lastCalledLabel(l);return `<button class="lead-choice" type="button" data-lead-id="${esc(l.id)}"><span class="choice-icon"><i class="bi bi-building"></i></span><span class="choice-main"><strong>${esc(clean(l.company,'Unnamed business'))}</strong><span>${esc(clean(l.name,'No contact name'))} · ${esc(sub)}</span><span class="site-preview-state${hp?'':' missing'}">${hp?'Has site preview':'Does not have site preview'}</span></span><span class="choice-status status-${c}">${categoryLabel(c)}</span><i class="bi bi-chevron-right choice-chevron"></i></button>`}).join(''):'<div class="directory-empty">No leads in this view.</div>'}
async function load(){const {data,error}=await client.from('crm').select('*').order('company',{ascending:true});if(error)throw error;leads=data||[];renderDirectory()}
function showDirectory(){active=null;$('#detailView').hidden=true;$('#directoryView').hidden=false;$('#pageTitle').textContent='Select a Lead';renderDirectory()}
function formatPhone(v){return clean(v,'No phone number')}
function showDetail(id){active=leads.find(l=>String(l.id)===String(id));if(!active)return;$('#directoryView').hidden=true;$('#detailView').hidden=false;$('#pageTitle').textContent='CRM';$('#detailCompany').textContent=clean(active.company,'Unnamed business');$('#detailContact').textContent=`${clean(active.name,'No contact name')} · ${formatPhone(active.phone)}`;$$('[data-field]').forEach(el=>{const key=el.dataset.field;el.value=active[key]??''});tags=Array.isArray(active.tags)?[...active.tags]:[];sources=Array.isArray(active.sources)?[...active.sources]:[];renderPills();renderPreviewActions()}
function renderPills(){$('#tagButtons').innerHTML=tags.length?tags.map((t,i)=>`<button class="tag-btn" type="button" data-remove-tag="${i}">${esc(t)} <i class="bi bi-x-lg"></i></button>`).join(''):'<span style="color:var(--muted);font-size:12px">No tags yet.</span>';$('#sourceButtons').innerHTML=sources.length?sources.map((t,i)=>`<button class="tag-btn" type="button" data-remove-source="${i}">${esc(t)} <i class="bi bi-x-lg"></i></button>`).join(''):'<span style="color:var(--muted);font-size:12px">No sources yet.</span>'}
function renderPreviewActions(){const items=[];const preview=clean(active.previewurl)||(clean(active.sitekey)?`https://viewyoursite.today/Sites/${encodeURIComponent(active.sitekey)}/`:'');if(preview)items.push(`<a href="${esc(preview)}" target="_blank"><i class="bi bi-box-arrow-up-right"></i>&nbsp;Preview</a>`);if(clean(active.liveurl))items.push(`<a href="${esc(active.liveurl)}" target="_blank"><i class="bi bi-globe"></i>&nbsp;Live Site</a>`);$('#previewActions').innerHTML=items.join('')}
function addPill(kind){const input=$(kind==='tag'?'#tagInput':'#sourceInput'),value=clean(input.value);if(!value)return;const list=kind==='tag'?tags:sources;if(!list.some(x=>String(x).toLowerCase()===value.toLowerCase()))list.push(value);input.value='';renderPills()}
async function saveLead(){if(!active)return;const patch={};$$('[data-field]').forEach(el=>patch[el.dataset.field]=el.value);patch.tags=tags;patch.sources=sources;patch.updated=new Date().toISOString();const b=$('#saveLead');b.disabled=true;$('#saveStatus').textContent='Saving…';const {error}=await client.from('crm').update(patch).eq('id',active.id);b.disabled=false;if(error){$('#saveStatus').textContent='Could not save.';toast(error.message);return}Object.assign(active,patch);$('#detailCompany').textContent=clean(active.company,'Unnamed business');$('#detailContact').textContent=`${clean(active.name,'No contact name')} · ${formatPhone(active.phone)}`;$('#saveStatus').textContent='Saved.';renderDirectory();renderPreviewActions();toast('CRM record saved')}
async function deleteLead(){if(!active)return;const label=clean(active.company,'this lead');if(!confirm(`Delete ${label}? This permanently removes this CRM record.`))return;const b=$('#deleteLead');b.disabled=true;const {error}=await client.from('crm').delete().eq('id',active.id);b.disabled=false;if(error){toast(error.message||'Could not delete lead');return}leads=leads.filter(l=>l.id!==active.id);toast('Lead deleted');showDirectory()}
$('#leadList').onclick=e=>{const b=e.target.closest('[data-lead-id]');if(b)showDetail(b.dataset.leadId)};
$('#backButton').onclick=showDirectory;$('#saveLead').onclick=saveLead;$('#deleteLead').onclick=deleteLead;$('#refreshLeads').onclick=async()=>{try{await load();toast('Leads refreshed')}catch(e){toast(e.message||'Could not refresh')}};$('#directorySearch').oninput=renderDirectory;
$('.category-tabs').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;directoryCategory=b.dataset.category;$$('[data-category]').forEach(x=>x.classList.toggle('active',x===b));renderDirectory()};
$('.site-filter-tabs').onclick=e=>{const b=e.target.closest('[data-site-filter]');if(!b)return;siteFilterMode=b.dataset.siteFilter;$$('[data-site-filter]').forEach(x=>x.classList.toggle('active',x===b));renderDirectory()};
$('#addTag').onclick=()=>addPill('tag');$('#addSource').onclick=()=>addPill('source');$('#tagInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addPill('tag')}};$('#sourceInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addPill('source')}};
$('#tagButtons').onclick=e=>{const b=e.target.closest('[data-remove-tag]');if(!b)return;tags.splice(Number(b.dataset.removeTag),1);renderPills()};$('#sourceButtons').onclick=e=>{const b=e.target.closest('[data-remove-source]');if(!b)return;sources.splice(Number(b.dataset.removeSource),1);renderPills()};
load().catch(e=>{$('#directoryStatus').textContent=e.message||'Could not load leads'});
